### ISSUE TITLE
Time from a game to another

### ISSUE THREAD

**Issue by NonSonoPisa** [NonSonoPisa/Blackjack#1]
Abbiamo avuto un problema nel riuscire a fissare un "wait" nel momento in cui uno dei due giocatori arriva a 26. L'idea sarebbe di realizzarlo con una wait di minimo 2 secondi, il problema è che abbiamo avuto un po' di issues nel realizzarlo siccome se viene inserito un timer troppo alto si bugga e non fa più ricominciare oppure la fa finire istantaneamente appena uno dei due giocatori arriva a 26. Avevamo questa idea perché se il timer tra una partita e l'altra è troppo veloce non si visualizza il messaggio di win.

**Comment by Mehrko** [comment]
ma sei un coglione Pisa ahahahha. Prova a mettere una wait in ms
